"""Add autoincrement to user_id

Revision ID: 038fd2598155
Revises: 9914f5b2859c
Create Date: 2024-05-15 21:19:59.534979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038fd2598155'
down_revision = '9914f5b2859c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
