"""更新 post_id 为自动增长

Revision ID: a985de51c788
Revises: 038fd2598155
Create Date: 2024-05-16 17:21:32.263683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a985de51c788'
down_revision = '038fd2598155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('answer_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Integer(),
               existing_nullable=True)
        

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Integer(),
               existing_nullable=True)
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.alter_column('post_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['post_id'])
        batch_op.alter_column('post_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
        batch_op.alter_column('answer_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
